# 特征工程配置

# 正则表达式模板
regex_patterns:
  # 选项触发符（支持全角半角）
  option_trigger: '^[A-Fａ-ｆ][\.\、\)\]）】]?\s+'
  
  # 答案模式
  answer_patterns:
    single_letter: '^[A-F]$'
    multi_letter: '^[A-F]{2,6}$'
    true_false: '^(对|错|√|×|True|False|T|F|正确|错误|是|否)$'
    blank_markers: '_{2,}|（\s*）|\(\s*\)|【\s*】'
  
  # 题干清理
  question_cleanup:
    tail_answer: '（?[对错√×TrueFalseTtFf]{1,5}）?$|(?:\s*[:：]\s*)?(对|错|√|×|True|False|T|F)$'
    answer_prefix: '答案?[:：].*$|正确答案[:：].*$|参考答案[:：].*$'

# 关键词词典
keywords:
  # 多选题提示词
  multiple_choice:
    - "多选"
    - "多项"
    - "至少两项"
    - "两个以上"
    - "不止一个"
    - "哪些"
    - "哪几个"
    - "包括"
    # 电力专业多选词汇
    - "保护装置"
    - "安全措施"
    - "操作规程"
    - "技术措施"
    - "防护用品"
    - "检修项目"
    - "试验项目"
    - "监控设备"
  
  # 判断题提示词
  true_false:
    - "判断对错"
    - "是否正确"
    - "对吗"
    - "对么"
    - "是非题"
    - "判断题"
    - "说法"
    - "表述"
    # 电力专业判断词汇
    - "符合规程"
    - "违反规定"
    - "安全规范"
    - "技术标准"
    - "操作要求"
    - "允许"
    - "禁止"
    - "必须"
    - "应当"
    - "不得"
  
  # 填空题提示词
  fill_blank:
    - "填写"
    - "填入"
    - "应填"
    - "等于"
    - "约为"
    - "标准"
    - "规定"
    # 电力专业填空词汇
    - "额定"
    - "容量"
    - "电压等级"
    - "频率"
    - "功率"
    - "电流"
    - "电压"
    - "阻抗"
    - "参数"
    - "数值"
    - "范围"
    - "限值"
  
  # 简答题提示词
  subjective:
    - "简述"
    - "说明"
    - "论述"
    - "分析"
    - "阐述"
    - "解释"
    - "描述"
    - "如何"
    - "为什么"
    - "什么是"
    - "怎样"
    - "请"
    - "试"
    - "谈谈"
    - "基本要求"
    - "工作原理"
    - "主要特点"
    - "注意事项"
    # 电力专业简答词汇
    - "操作步骤"
    - "检修方法"
    - "故障处理"
    - "安全要求"
    - "技术原理"
    - "运行方式"
    - "维护保养"
    - "应急处理"
    - "预防措施"
    - "改进建议"

# 电力专业词汇扩展
power_industry_keywords:
  # 设备类
  equipment:
    - "变压器"
    - "开关"
    - "断路器"
    - "隔离开关"
    - "接地刀闸"
    - "电缆"
    - "母线"
    - "避雷器"
    - "电容器"
    - "电抗器"
    - "互感器"
    - "继电器"
    - "控制柜"
    - "配电箱"
  
  # 操作类
  operations:
    - "投运"
    - "停运"
    - "切换"
    - "倒闸"
    - "检修"
    - "试验"
    - "巡视"
    - "监控"
    - "调度"
    - "操作"
    - "维护"
    - "保养"
  
  # 安全类
  safety:
    - "接地"
    - "验电"
    - "挂牌"
    - "围栏"
    - "标示牌"
    - "安全帽"
    - "绝缘靴"
    - "绝缘手套"
    - "安全带"
    - "防护服"
    - "工作票"
    - "操作票"
  
  # 技术参数类
  parameters:
    - "千伏"
    - "千瓦"
    - "兆瓦"
    - "安培"
    - "赫兹"
    - "欧姆"
    - "法拉"
    - "亨利"
    - "功率因数"
    - "短路电流"
    - "绝缘电阻"

# 停用词
stopwords:
  - "的"
  - "了"
  - "在"
  - "是"
  - "我"
  - "有"
  - "和"
  - "就"
  - "不"
  - "人"
  - "都"
  - "一"
  - "一个"
  - "上"
  - "也"
  - "很"
  - "到"
  - "说"
  - "要"
  - "去"
  - "你"
  - "会"
  - "着"
  - "没有"
  - "看"
  - "好"
  - "自己"
  - "这"

# 特征权重配置
feature_weights:
  layout_score: 1.0
  option_count: 1.5
  answer_pattern: 2.0
  keyword_match: 1.2
  question_length: 0.8
  punct_density: 0.6

# 归一化配置
normalization:
  # 全角半角映射
  fullwidth_to_halfwidth:
    "Ａ": "A"
    "Ｂ": "B"
    "Ｃ": "C"
    "Ｄ": "D"
    "Ｅ": "E"
    "Ｆ": "F"
    "（": "("
    "）": ")"
    "。": "."
    "，": ","
  
  # OCR符号映射
  ocr_symbol_mapping:
    "∨": "√"
    "v": "√"
    "V": "√"
    "x": "×"
    "X": "×"
    "*": "×"
    "TRUE": "True"
    "FALSE": "False"
    "YES": "Yes"
    "NO": "No"
